import { Category, Product } from './types';

export const categories: Category[] = [
  { id: 'bedding', name: 'Постельное белье', code: 'bedding' },
  { id: 'basics', name: 'Подушки и одеяла', code: 'basics' },
  { id: 'bath', name: 'Ванная комната', code: 'bath' },
  { id: 'decor', name: 'Пледы и декор', code: 'decor' },
  { id: 'curtains', name: 'Шторы и тюль', code: 'curtains' },
  { id: 'table', name: 'Столовый текстиль', code: 'table' },
  { id: 'kids', name: 'Детский текстиль', code: 'kids' },
];

export const retiredExternalCodes = ['DESELI-LINEN-MILK'];

const imageAliases: Record<string, string> = {
  'sateen-rose': 'rose-cloud',
  'percale-white': 'pearl-morning',
  'jacquard-graphite': 'antique-violet',
  'tencel-blue': 'blue-breeze',
  'flannel-warm': 'warm-sand',
  'duvet-air': 'air-season',
  'duvet-wool': 'soft-quilt',
  'pillow-cloud': 'cloud-balance',
  'pillow-ortho': 'cloud-balance',
  'mattress-cover': 'milk-linen',
  'bamboo-towels': 'bamboo-touch',
  'terry-towel': 'spa-waffle',
  'waffle-robe': 'spa-waffle',
  'bath-mat': 'soft-quilt',
  'cashmere-throw': 'lavender-ruffle',
  'cushion-set': 'heart-charm',
  'roman-shade': 'milk-canopy',
  'velvet-drape': 'antique-violet',
  'apron-home': 'classic-linen',
  'kids-bedding': 'milk-canopy',
  'muslin-blanket': 'rose-cloud',
};

const realImages: Record<string, string> = {
  'sateen-rose': '/Premium_sateen_bedding_set_202606012131.jpeg',
  'percale-white': '/Luxury_bedding_set_sateen_202606012131.jpeg',
  'jacquard-graphite': '/Bedroom_interior_with_grey_bedding_202606012131.jpeg',
  'tencel-blue': '/Duvet_and_pillows_on_bed_202606012131.jpeg',
  'flannel-warm': '/Bedding_set_folded_on_bed_202606012131.jpeg',
  'duvet-air': '/Duvet_and_pillows_on_bed_202606012131_2.jpeg',
  'duvet-wool': '/Duvet_and_pillows_on_bed_202606012131.jpeg',
  'pillow-cloud': '/Pillow_and_blanket_texture_202606012131.jpeg',
  'pillow-ortho': '/Pillow_and_blanket_texture_202606012131.jpeg',
  'mattress-cover': '/Pillow_and_blanket_texture_202606012131.jpeg',
  'bamboo-towels': '/Cotton_towels_in_bathroom_setting_202606012131.jpeg',
  'terry-towel': '/Waffle-weave_towel_and_bath_towel_202606012131.jpeg',
  'waffle-robe': '/Cotton_bathrobe_hanging_in_bathroom_202606012131.jpeg',
  'bath-mat': '/Cotton_towels_in_bathroom_setting_202606012131.jpeg',
  'soft-quilt': '/Pillows_and_throw_blanket_texture_202606012131.jpeg',
  'warm-sand': '/Pillows_and_throw_blanket_texture_202606012131.jpeg',
  'cashmere-throw': '/Pillows_and_throw_blanket_texture_202606012131.jpeg',
  'cushion-set': '/Sewing_accessories_fabric_swatch_202606012131.jpeg',
  'blackout-linen': '/Bedroom_interior_with_grey_bedding_202606012131.jpeg',
  'organdy-mist': '/Fabric_rolls_in_workshop_202606012131.jpeg',
  'roman-shade': '/Fabric_rolls_in_workshop_202606012131.jpeg',
  'velvet-drape': '/Fabric_rolls_in_workshop_202606012131.jpeg',
  'provence-dinner': '/Sewing_accessories_fabric_swatch_202606012131.jpeg',
  'classic-linen': '/Sewing_accessories_fabric_swatch_202606012131.jpeg',
  'botanical-stitch': '/Sewing_accessories_fabric_swatch_202606012131.jpeg',
  'apron-home': '/Sewing_accessories_fabric_swatch_202606012131.jpeg',
  'bunny-hug': '/Waffle-weave_towel_and_bath_towel_202606012131.jpeg',
  'kids-bedding': '/Duvet_and_pillows_on_bed_202606012131.jpeg',
  'muslin-blanket': '/Premium_sateen_bedding_set_202606012131.jpeg',
  'milk-canopy': '/Fabric_rolls_in_workshop_202606012131.jpeg',
};

const image = (slug: string) => realImages[slug] ?? `/products/${imageAliases[slug] ?? slug}.svg`;

const p = (
  id: string,
  title: string,
  category: Product['category'],
  price: number,
  colors: string[],
  sizes: string[],
  description: string,
  specs: Record<string, string>,
  flags: Partial<Product> = {},
): Product => ({
  id,
  externalCode: `DESELI-${id.replace('deseli-', '').toUpperCase()}`,
  title,
  price,
  image: image(id.replace('deseli-', '')),
  colors,
  sizes,
  category,
  gender: 'all',
  inStock: true,
  description,
  specs,
  ...flags,
});

export const deseliProducts: Product[] = [
  p('deseli-sateen-rose', 'Комплект сатинового белья Rose Cloud', 'bedding', 10900, ['#EFCAD0', '#F7E8E2'], ['Евро', 'Семейный'], 'Гладкий сатин с мягким розовым оттенком, аккуратной окантовкой и спокойным гостиничным ощущением.', { Состав: '100% хлопок-сатин', Комплект: 'пододеяльник, простыня, 2 наволочки', Плотность: '220 TC' }, { isHot: true }),
  p('deseli-percale-white', 'Комплект перкаль Hotel White', 'bedding', 9800, ['#FFFFFF', '#F2EFE8'], ['1.5-сп', 'Евро', 'Семейный'], 'Плотная белая перкаль для свежей, хрустящей постели в стиле хорошего отеля.', { Состав: '100% длинноволокнистый хлопок', Плетение: 'перкаль', Застежка: 'пуговицы' }, { isNew: true }),
  p('deseli-jacquard-graphite', 'Жаккардовый комплект Graphite Line', 'bedding', 14600, ['#5E5A60', '#D7CEC2'], ['Евро', 'King size'], 'Сдержанный жаккард с тонким геометрическим рельефом для современной спальни.', { Состав: 'хлопок-жаккард', Узор: 'тонкая геометрия', Уход: 'деликатная стирка' }),
  p('deseli-tencel-blue', 'Комплект из тенселя Blue Breeze', 'bedding', 15800, ['#9EC9D9', '#E8F2F3'], ['Евро', 'Семейный'], 'Шелковистый прохладный тенсель для летнего сна и мягкого скольжения ткани.', { Состав: '100% тенсель', Сезон: 'лето / всесезон', Детали: 'кант по периметру' }, { isNew: true }),
  p('deseli-flannel-warm', 'Фланелевый комплект Warm Cotton', 'bedding', 8900, ['#DCC4A7', '#8B8278'], ['1.5-сп', 'Евро'], 'Теплая хлопковая фланель с легким ворсом для холодного сезона.', { Состав: '100% хлопок', Сезон: 'осень / зима', Плотность: '170 г/м²' }, { salePrice: 7900, isSale: true }),
  p('deseli-duvet-air', 'Одеяло Air Season', 'basics', 8400, ['#F7F0E7'], ['1.5-сп', 'Евро', 'King size'], 'Всесезонное легкое одеяло с кассетной стежкой и дышащим хлопковым чехлом.', { Чехол: '100% хлопок', Наполнитель: 'микроволокно', Теплота: 'всесезонное' }, { isHot: true }),
  p('deseli-duvet-wool', 'Одеяло Merino Warm', 'basics', 11200, ['#EFE4D3'], ['Евро', 'King size'], 'Теплое одеяло с шерстью мериноса для прохладной спальни.', { Чехол: 'сатин', Наполнитель: 'мериносовая шерсть', Теплота: 'зимнее' }),
  p('deseli-pillow-cloud', 'Подушка Cloud Balance', 'basics', 3900, ['#FFFFFF'], ['50x70 см', '70x70 см'], 'Упругая подушка средней высоты с хлопковым чехлом и гипоаллергенным наполнителем.', { Чехол: 'хлопковый сатин', Наполнитель: 'микроволокно', Жесткость: 'средняя' }),
  p('deseli-pillow-ortho', 'Подушка Ortho Support', 'basics', 5200, ['#F4EFE6'], ['40x60 см'], 'Анатомическая подушка с поддержкой шеи для ежедневного сна.', { Чехол: 'трикотаж', Наполнитель: 'memory foam', Высота: '12 см' }, { isNew: true }),
  p('deseli-mattress-cover', 'Наматрасник Clean Sleep', 'basics', 4600, ['#FFFFFF'], ['160x200 см', '180x200 см'], 'Защитный наматрасник с мягкой хлопковой поверхностью и резинками по углам.', { Верх: 'хлопок', Защита: 'дышащая мембрана', Крепление: 'резинки' }),
  p('deseli-bamboo-towels', 'Набор полотенец Bamboo Touch', 'bath', 5200, ['#E8D7C5', '#F6F1EA', '#B7C1B1'], ['3 шт', '5 шт'], 'Мягкие полотенца из хлопка и бамбука с высокой впитываемостью.', { Состав: '70% хлопок, 30% бамбук', Плотность: '500 г/м²', Комплект: 'лицо, руки, банное' }, { isHot: true }),
  p('deseli-terry-towel', 'Банное полотенце Terry Spa', 'bath', 2400, ['#FFFFFF', '#D8C1A4', '#9EC9D9'], ['70x140 см', '100x150 см'], 'Плотная махра для ванной комнаты, бассейна и гостевого комплекта.', { Состав: '100% хлопок', Плотность: '550 г/м²', Край: 'двойной бордюр' }),
  p('deseli-waffle-robe', 'Вафельный халат Spa Waffle', 'bath', 6900, ['#FFFFFF', '#D8C1A4'], ['S/M', 'L/XL'], 'Легкий вафельный халат для дома, бани и гостиничного образа.', { Состав: '100% хлопок', Плотность: '240 г/м²', Детали: 'пояс, карманы' }),
  p('deseli-bath-mat', 'Коврик для ванной Soft Step', 'bath', 3100, ['#EFE4D3', '#8B8278'], ['50x80 см', '60x90 см'], 'Мягкий коврик с плотным ворсом и нескользящей основой.', { Ворс: 'микрохлопок', Основа: 'антискользящая', Уход: 'машинная стирка' }),
  p('deseli-soft-quilt', 'Стеганое покрывало Soft Quilt', 'decor', 11900, ['#D8C1A4', '#EFE4D3'], ['220x240 см', '240x260 см'], 'Фактурное покрывало с мягкой стежкой для кровати, дивана или интерьерной съемки.', { Материал: 'микровелюр', Наполнитель: 'синтепух', Стежка: 'ромб' }),
  p('deseli-warm-sand', 'Вязаный плед Warm Sand', 'decor', 7900, ['#C8A889', '#E9DAC4'], ['140x200 см', '180x220 см'], 'Фактурный плед крупной вязки в теплой песочной гамме.', { Состав: 'шерсть / акрил', Уход: 'деликатная стирка', Фактура: 'крупная вязка' }),
  p('deseli-cashmere-throw', 'Плед Cashmere Touch', 'decor', 9600, ['#B9A1C8', '#D6C3A5'], ['130x180 см'], 'Тонкий мягкий плед для дивана, кресла и подарочной упаковки.', { Состав: 'шерсть / кашемир', Край: 'бахрома', Сезон: 'всесезон' }, { isNew: true }),
  p('deseli-cushion-set', 'Набор декоративных подушек Calm Sofa', 'decor', 3900, ['#F0B8C8', '#B7C1B1', '#D8C1A4'], ['45x45 см (2 шт)'], 'Пара декоративных чехлов для дивана или спальни в мягкой природной палитре.', { Материал: 'хлопок-велюр', Комплект: '2 чехла', Застежка: 'потайная молния' }),
  p('deseli-blackout-linen', 'Шторы Blackout Linen Look', 'curtains', 7600, ['#D6C3A5', '#8B8278', '#F6F1EA'], ['150x270 см (2 шт)', '200x270 см (2 шт)'], 'Плотные шторы с фактурой льна и затемнением для спальни или гостиной.', { Затемнение: 'до 90%', Материал: 'полиэстер с фактурой льна', Крепление: 'шторная лента' }, { salePrice: 6400, isSale: true }),
  p('deseli-organdy-mist', 'Тюль Organdy Mist', 'curtains', 4200, ['#FFFFFF', '#F7F0E7'], ['300x270 см', '400x270 см'], 'Воздушная тюль с мягким рассеиванием света и аккуратной лентой.', { Материал: 'органза', Высота: '270 см', Крепление: 'шторная лента' }),
  p('deseli-roman-shade', 'Римская штора Linen Shade', 'curtains', 5900, ['#EFE4D3', '#B7C1B1'], ['80x160 см', '100x160 см'], 'Лаконичная римская штора для кухни, кабинета или детской.', { Материал: 'смесовый лен', Механизм: 'цепочный', Монтаж: 'стена / потолок' }),
  p('deseli-velvet-drape', 'Портьеры Velvet Evening', 'curtains', 12800, ['#927894', '#4A5568'], ['150x270 см (2 шт)'], 'Тяжелые велюровые портьеры с мягким матовым переливом.', { Материал: 'бархат', Подкладка: 'есть', Затемнение: '85%' }),
  p('deseli-provence-dinner', 'Скатерть Provence Dinner', 'table', 4900, ['#EFE4D3', '#FFFFFF', '#C8A889'], ['140x180 см', '140x240 см', '160x300 см'], 'Скатерть для домашней сервировки и праздничного стола.', { Состав: 'хлопок / лен', Край: 'широкая подгибка', Уход: 'стирка при 40°C' }),
  p('deseli-classic-linen', 'Набор салфеток Classic Linen', 'table', 2300, ['#FFFFFF', '#EFE4D3', '#B9A1C8'], ['40x40 см (6 шт)', '50x50 см (6 шт)'], 'Комплект тканевых салфеток с аккуратным краем для законченной сервировки.', { Состав: 'лен / хлопок', Комплект: '6 салфеток', Детали: 'мережковая строчка' }),
  p('deseli-botanical-stitch', 'Настольный раннер Botanical Stitch', 'table', 3400, ['#F2E7D8', '#B7C1B1'], ['40x140 см', '40x200 см'], 'Раннер с деликатной растительной вышивкой для сервировки и предметной съемки.', { Материал: 'хлопок / лен', Вышивка: 'ботанический мотив', Край: 'бахрома' }, { isHot: true }),
  p('deseli-apron-home', 'Фартук Kitchen Linen', 'table', 2800, ['#C8A889', '#8B8278'], ['ONE SIZE'], 'Практичный фартук из плотной ткани для кухни, сервировки и подарочного набора.', { Материал: 'хлопок / лен', Карманы: '2 шт', Регулировка: 'завязки' }),
  p('deseli-bunny-hug', 'Детский халат Bunny Hug', 'kids', 4200, ['#F3C7D8', '#DDEBF1'], ['1-3 года', '3-5 лет', '5-7 лет'], 'Мягкий детский халат с капюшоном и ушками для ванной и бассейна.', { Состав: 'хлопковая махра', Плотность: '430 г/м²', Детали: 'капюшон, пояс, карманы' }, { isNew: true }),
  p('deseli-kids-bedding', 'Детский комплект Little Cloud', 'kids', 7200, ['#DDEBF1', '#F8EDE1'], ['Детский', 'Подростковый'], 'Нежный комплект для детской кровати с мягкой хлопковой поверхностью.', { Состав: '100% хлопок', Комплект: '3 предмета', Рисунок: 'однотонный' }),
  p('deseli-muslin-blanket', 'Муслиновый плед Baby Muslin', 'kids', 3600, ['#F5D7E4', '#B7C1B1'], ['100x120 см'], 'Легкий многослойный муслиновый плед для коляски и кроватки.', { Состав: '100% хлопок-муслин', Слои: '4', Уход: 'стирка при 30°C' }),
  p('deseli-milk-canopy', 'Детский балдахин Milk Canopy', 'kids', 6900, ['#F8EDE1', '#F5D7E4'], ['260 см'], 'Легкий балдахин с крупными завязками для детской комнаты.', { Материал: 'муслин', Высота: '260 см', Крепление: 'петля / потолочный крюк' }),
];

export const heroSlides = [
  {
    image: '/Duvet_and_pillows_on_bed_202606012131.jpeg',
    eyebrow: 'Домашний текстиль на каждый день',
    title: 'Тихая роскошь\nдля спальни',
    text: 'Сатин, перкаль, тенсель и мягкие базовые изделия для собранного интерьера.',
    category: 'bedding' as const,
  },
  {
    image: '/Cotton_bathrobe_hanging_in_bathroom_202606012131.jpeg',
    eyebrow: 'Ванная как спа',
    title: 'Мягкость после\nкаждого душа',
    text: 'Полотенца, халаты и коврики в спокойной палитре для ежедневного комфорта.',
    category: 'bath' as const,
  },
  {
    image: '/Pillows_and_throw_blanket_texture_202606012131.jpeg',
    eyebrow: 'Текстиль для атмосферы',
    title: 'Слои фактур\nв гостиной',
    text: 'Пледы, шторы, подушки и столовый текстиль, которые собирают пространство.',
    category: 'decor' as const,
  },
];

export const heroImage = heroSlides[0].image;